// Wrappedbulls: ERC404-style hybrid token-NFT layer for pump.fun-launched tokens.
//
// Pump.fun launches standard SPL tokens (no transfer hooks). SPL-404 exists
// on Solana but requires Token-2022 — incompatible with pump.fun. Wrappedbulls
// bridges that gap with an NFT-owned vault PDA pattern: each bull NFT has
// a vault holding 1,000,000 of the underlying $TOKEN, and the vault's
// authority is derived from the NFT's mint address.
//
// Result: when an NFT trades on Magic Eden / Tensor, the locked tokens
// follow the NFT atomically. Buy the NFT → you control the vault. Sell
// the NFT → the buyer controls the vault. ERC404-style inseparability
// without modifying the underlying token.
//
// Two user-initiated instructions:
//   - wrap_bull: lock 1M $TOKEN into a fresh NFT (caller must hold ≥1M).
//   - unwrap_bull: burn the NFT and release the 1M $TOKEN (caller must
//     hold the NFT).
//
// The off-chain renderer seeds visuals from the NFT mint address, so the
// art is locked at wrap time and stays with the NFT through transfers.

use anchor_lang::prelude::*;

pub mod state;
pub mod instructions;
pub mod errors;

use instructions::*;

// Program ID (matches target/deploy/wrappedbulls-keypair.json on the dev box).
// Kept as a literal here because `declare_id!` is a procedural macro
// that requires a string literal at the call site (it cannot accept a
// `const &str`). The same value also appears in `config/launch.toml`
// under `[program] id =`. The clone script (P2.6) updates both in
// lockstep when scaffolding a new project. If they disagree, the
// program will load but the on-chain ID won't match expectations.
declare_id!("F7qXskG73efUwbDo2B97tZgpPAqX7zHMApXbPUimcFdS");

// ---- Protocol constants ----
//
// Every constant below is auto-generated by build.rs from
// config/launch.toml. To change any of them, edit the config and
// re-run `anchor build`. Do NOT add new hardcoded constants here —
// add them to config/launch.toml and extend build.rs.
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

#[program]
pub mod wrappedbulls {
    use super::*;

    /// One-time setup: creates the BullBank singleton PDA and locks the
    /// $TOKEN mint address. The mint is immutable thereafter — switching
    /// mints requires a fresh deployment.
    pub fn initialize(ctx: Context<Initialize>, token_mint: Pubkey) -> Result<()> {
        instructions::initialize::handler(ctx, token_mint)
    }

    /// One-time setup: creates the Metaplex Certified Collection (MCC)
    /// parent NFT. Must be called by `bank.authority` exactly once. After
    /// this, every wrap_bull verifies its NFT into this collection so
    /// Magic Eden / Tensor / Phantom recognise the bulls as a real
    /// collection (no DYOR warnings, searchable by collection, floor
    /// pricing surfaces).
    pub fn initialize_collection(ctx: Context<InitializeCollection>) -> Result<()> {
        instructions::initialize_collection::handler(ctx)
    }

    /// Wrap 1M $TOKEN into a fresh bull NFT.
    ///
    /// Caller must:
    ///   1. Generate a fresh keypair for the NFT mint client-side
    ///   2. Pre-compute the next tier_index from BullBank state
    ///   3. Sign as both `payer` and `nft_mint` keypair
    ///
    /// The 1M tokens are transferred from the caller's $TOKEN account into
    /// a vault PDA derived from the new NFT mint. The vault's authority is
    /// `PDA(["vault", nft_mint])`, so whoever holds the NFT controls the
    /// vault via this program. The Metaplex NFT is fully tradeable on
    /// Magic Eden / Tensor / any standard marketplace.
    pub fn wrap_bull(ctx: Context<WrapBull>, tier_index: u16) -> Result<()> {
        instructions::wrap_bull::handler(ctx, tier_index)
    }

    /// Unwrap a bull NFT, releasing the locked 1M $TOKEN to the caller.
    ///
    /// Caller must hold 1 of the bull's NFT in their ATA. Verified on-chain.
    /// After this instruction:
    ///   - 1M $TOKEN flows from vault → caller
    ///   - NFT mint, ATA, metadata, master edition, and BullAsset are closed
    ///   - tier_index goes back onto the free_tiers stack for reuse
    ///   - Reused tiers re-roll their visual (new NFT mint = new seed)
    pub fn unwrap_bull(ctx: Context<UnwrapBull>, tier_index: u16) -> Result<()> {
        instructions::unwrap_bull::handler(ctx, tier_index)
    }
}
