#!/usr/bin/env node
// sync_web_config.mjs — reads config/launch.toml at the workspace root
// and writes web/lib/launch-config.generated.ts. Run automatically by
// the `predev` / `prebuild` hooks in web/package.json so the web side
// always has fresh, project-specific constants without a runtime TOML
// parser. Keep this generator dep-free so it works pre-`npm install`.
//
// The web side imports the generated module via:
//   import { LAUNCH_CONFIG } from "@/lib/launch-config.generated";
//
// This is half of the brand system. The other half is web/config/brand.json
// (humans-edit, web-only). web/lib/brand.ts merges both into a single
// `getBrand()` helper.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Resolve repo paths relative to this script — works regardless of cwd.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const TOML_PATH = path.join(ROOT, "config", "launch.toml");
const OUT_PATH = path.join(ROOT, "web", "lib", "launch-config.generated.ts");

// --- Minimal TOML parser for our schema -------------------------------
// We don't ship a TOML dep. launch.toml uses only:
//   - line comments starting with `#`
//   - `[section]` headers
//   - `key = value` where value is one of: "string", integer, float, bool
//   - integer literals may contain `_` separators (e.g. 1_000_000)
// This parser handles exactly that subset. If the schema grows, vendor
// a real parser; do not "extend" this one.
function parseToml(raw) {
  const result = {};
  let current = result;
  const lines = raw.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    // Strip comments and trim.
    const noComment = rawLine.replace(/\s+#.*$/, "").replace(/^#.*$/, "").trim();
    if (!noComment) continue;

    // Section header.
    const section = noComment.match(/^\[([\w\.]+)\]$/);
    if (section) {
      const name = section[1];
      if (name.includes(".")) {
        throw new Error(
          `sync_web_config: nested tables (${name}) not supported`,
        );
      }
      result[name] = result[name] ?? {};
      current = result[name];
      continue;
    }

    // key = value
    const kv = noComment.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
    if (!kv) {
      throw new Error(`sync_web_config: unparseable line ${i + 1}: ${rawLine}`);
    }
    const key = kv[1];
    const valueRaw = kv[2].trim();

    let value;
    if (valueRaw.startsWith('"') && valueRaw.endsWith('"')) {
      value = valueRaw.slice(1, -1);
    } else if (valueRaw === "true" || valueRaw === "false") {
      value = valueRaw === "true";
    } else if (/^-?\d[\d_]*$/.test(valueRaw)) {
      value = parseInt(valueRaw.replace(/_/g, ""), 10);
    } else if (/^-?\d[\d_]*\.\d+$/.test(valueRaw)) {
      value = parseFloat(valueRaw.replace(/_/g, ""));
    } else {
      throw new Error(
        `sync_web_config: unsupported value at line ${i + 1}: ${valueRaw}`,
      );
    }
    current[key] = value;
  }
  return result;
}

const tomlRaw = fs.readFileSync(TOML_PATH, "utf8");
const cfg = parseToml(tomlRaw);

// Sanity-check required fields. Fail loud — a silently malformed config
// is the kind of bug that surfaces during launch.
const required = {
  "project.name": cfg.project?.name,
  "project.unit_singular": cfg.project?.unit_singular,
  "project.ticker": cfg.project?.ticker,
  "project.domain": cfg.project?.domain,
  "supply.max_supply": cfg.supply?.max_supply,
  "supply.tokens_per_nft": cfg.supply?.tokens_per_nft,
  "supply.token_decimals": cfg.supply?.token_decimals,
  "royalty.bps": cfg.royalty?.bps,
  "royalty.treasury_pubkey": cfg.royalty?.treasury_pubkey,
  "metadata.collection_uri": cfg.metadata?.collection_uri,
  "metadata.nft_uri_template": cfg.metadata?.nft_uri_template,
  "program.id": cfg.program?.id,
};
for (const [key, val] of Object.entries(required)) {
  if (val === undefined || val === null || val === "") {
    throw new Error(`sync_web_config: missing required config value '${key}'`);
  }
}

const tokensPerNftBase = BigInt(cfg.supply.tokens_per_nft) *
  10n ** BigInt(cfg.supply.token_decimals);

const generated =
`// AUTO-GENERATED by scripts/sync_web_config.mjs from config/launch.toml.
// DO NOT EDIT. Re-run \`node scripts/sync_web_config.mjs\` after editing
// the TOML, or just \`npm run dev\` / \`npm run build\` (the hooks invoke it).
//
// Source of truth for project-specific constants on the web side.
// Mirrors what build.rs writes into the on-chain program at compile time.

export const LAUNCH_CONFIG = {
  project: {
    name:          ${JSON.stringify(cfg.project.name)},
    unitSingular:  ${JSON.stringify(cfg.project.unit_singular)},
    ticker:        ${JSON.stringify(cfg.project.ticker)},
    domain:        ${JSON.stringify(cfg.project.domain)},
  },
  supply: {
    maxSupply:        ${cfg.supply.max_supply},
    tokensPerNft:     ${cfg.supply.tokens_per_nft},
    tokenDecimals:    ${cfg.supply.token_decimals},
    // Base-unit version, ready for direct comparison against raw
    // amounts from RPC. As a bigint to survive JS number precision.
    tokensPerNftBase: ${tokensPerNftBase}n,
  },
  royalty: {
    bps:             ${cfg.royalty.bps},
    treasuryPubkey:  ${JSON.stringify(cfg.royalty.treasury_pubkey)},
  },
  metadata: {
    collectionUri:   ${JSON.stringify(cfg.metadata.collection_uri)},
    nftUriTemplate:  ${JSON.stringify(cfg.metadata.nft_uri_template)},
  },
  program: {
    id:              ${JSON.stringify(cfg.program.id)},
  },
} as const;

export type LaunchConfig = typeof LAUNCH_CONFIG;
`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, generated);
console.log(`sync_web_config: wrote ${path.relative(ROOT, OUT_PATH)}`);
