// build.rs — reads config/launch.toml at compile time and writes
// $OUT_DIR/generated.rs with all project-specific constants. lib.rs
// includes the generated file via include!().
//
// To rebrand the program for a new project: edit config/launch.toml,
// run `anchor build`. No source edits required.
//
// Cargo invalidates this script (and rebuilds) whenever
// config/launch.toml changes, via the println!("cargo:rerun-if-changed=...")
// lines below.

use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(serde::Deserialize)]
struct Config {
    project: Project,
    supply: Supply,
    royalty: Royalty,
    metadata: Metadata,
    program: Program,
}

#[derive(serde::Deserialize)]
struct Project {
    name: String,
    #[allow(dead_code)]
    unit_singular: String,
    ticker: String,
    #[allow(dead_code)]
    domain: String,
}

#[derive(serde::Deserialize)]
struct Supply {
    max_supply: u16,
    tokens_per_nft: u64,
    token_decimals: u8,
}

#[derive(serde::Deserialize)]
struct Royalty {
    bps: u16,
    treasury_pubkey: String,
}

#[derive(serde::Deserialize)]
struct Metadata {
    collection_uri: String,
    nft_uri_template: String,
}

#[derive(serde::Deserialize)]
struct Program {
    id: String,
}

fn main() {
    // Resolve config path. CARGO_MANIFEST_DIR is programs/wrappedbulls/;
    // config lives at workspace root, two levels up.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("expected programs/<crate>/ inside a workspace")
        .to_path_buf();
    let config_path = workspace_root.join("config").join("launch.toml");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", config_path.display(), e));
    let cfg: Config = toml::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {}", config_path.display(), e));

    // Compute base-unit tokens-per-NFT: tokens_per_nft * 10^decimals.
    let tokens_per_nft_base: u128 =
        (cfg.supply.tokens_per_nft as u128) * 10u128.pow(cfg.supply.token_decimals as u32);
    let tokens_per_nft_base_u64: u64 = u64::try_from(tokens_per_nft_base)
        .expect("tokens_per_nft * 10^decimals overflows u64; reduce values in config");

    // Compose the NFT URI base. Convention says the template ends with
    // "{tier}". We split into prefix (everything before {tier}) so the
    // on-chain code can format!("{}{}", base, tier_index) without
    // pulling in a templating library.
    let nft_uri_base = cfg
        .metadata
        .nft_uri_template
        .strip_suffix("{tier}")
        .unwrap_or_else(|| {
            panic!(
                "metadata.nft_uri_template must end with '{{tier}}' (got: {})",
                cfg.metadata.nft_uri_template
            )
        });

    let generated = format!(
        r#"// AUTO-GENERATED by build.rs from config/launch.toml.
// DO NOT EDIT — re-run `cargo build` after editing the config file.

/// Project name (collection name + NFT name prefix is `"{} #N"`).
pub const PROJECT_NAME: &str = "{name}";

/// Ticker symbol (used as NFT symbol in Metaplex metadata).
pub const TICKER: &str = "{ticker}";

/// Maximum NFTs that can be wrapped at one time (cap).
pub const MAX_BULLS: u16 = {max_supply};

/// Tokens-per-NFT in base units (whole_tokens * 10^decimals).
pub const TOKENS_PER_BULL: u64 = {tokens_per_nft_base};

/// Token mint decimals (asserted on-chain via transfer_checked).
pub const TOKEN_DECIMALS: u8 = {token_decimals};

/// Secondary-sale royalty (basis points). 500 = 5%.
pub const ROYALTY_BPS: u16 = {royalty_bps};

/// Royalty treasury (also written as the on-chain creator).
pub const ROYALTY_TREASURY: ::anchor_lang::prelude::Pubkey =
    ::anchor_lang::prelude::pubkey!("{royalty_treasury}");

/// Collection-level metadata URI (used by initialize_collection).
pub const COLLECTION_URI: &str = "{collection_uri}";

/// Prefix for per-NFT metadata URI; per-wrap suffix is the tier index.
/// Full URI is `format!("{{}}{{}}", NFT_URI_BASE, tier_index)`.
pub const NFT_URI_BASE: &str = "{nft_uri_base}";

/// Anchor program ID (matches target/deploy/<name>-keypair.json).
pub const PROGRAM_ID_STR: &str = "{program_id}";
"#,
        name = cfg.project.name,
        ticker = cfg.project.ticker,
        max_supply = cfg.supply.max_supply,
        tokens_per_nft_base = tokens_per_nft_base_u64,
        token_decimals = cfg.supply.token_decimals,
        royalty_bps = cfg.royalty.bps,
        royalty_treasury = cfg.royalty.treasury_pubkey,
        collection_uri = cfg.metadata.collection_uri,
        nft_uri_base = nft_uri_base,
        program_id = cfg.program.id,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("generated.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));
}
